version: '3.7'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    network_mode: host
    volumes:
      - /opt/home-assistant/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    devices:
      - /dev/zwave0:/dev/zwave0
    restart: on-failure
    depends_on:
      - mosquitto
      - zigbee2mqtt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 6

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    network_mode: host
    volumes:
      - /opt/home-assistant/node-red:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: "no" # because the exit code(s) are wrong
    depends_on:
      - mosquitto
      - zigbee2mqtt
      - homeassistant
    environment:
      - TZ=America/New_York
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:1880"]
      interval: 30s
      timeout: 10s
      retries: 5

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.28.4
    user: "1000:1000"
    volumes:
      - /opt/home-assistant/zigbee2mqtt:/app/data
      # - /run/udev:/run/udev:ro
    devices:
      - /dev/zigbee2:/dev/ttyACM0
    restart: on-failure
    network_mode: host
    # privileged: true
    environment:
      - TZ=America/New_York
    depends_on:
      - mosquitto

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    user: "1000:1000"
    ports:
      - 1883:1883
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/home-assistant/mosquitto:/mosquitto/config
      - /opt/home-assistant/mosquitto:/mosquitto/data
    restart: on-failure

  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /opt/home-assistant/portainer:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no" # because the exit code(s) are wrong

  organizr:
    container_name: organizr
    image: organizr/organizr
    ports:
      - 10080:80
      - 10443:443
    volumes:
      - /opt/home-assistant/organizr:/config:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - PGID=1000
      - PUID=1000
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 5

  dockermon:
    container_name: dockermon
    image: philhawthorne/ha-dockermon
    ports:
      - 8126:8126
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/home-assistant/dockermon:/config
    restart: on-failure
